variables:
    TUTOR_PLUGIN: indigo
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: tutor-indigo
    TUTOR_IMAGES: openedx mfe
    GITHUB_REPO: overhangio/tutor-indigo

stages:
  - build
  - deploy


deploy_prod:
  stage: deploy
  script:
    - sudo cp -r * $TUTOR_DIR/tutor-indigo
    - source $TUTOR_DIR/venv/bin/activate
    - cd $TUTOR_DIR
    - sudo pip install -e ./tutor-indigo
    - tutor plugins enable indigo
    - tutor config save
    - sudo tutor images build openedx
    - sudo tutor local start -d
  tags:
    - edx
  only:
    refs:
      - master
