variables:
    TUTOR_PLUGIN: mexicoxmx
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: mexicoxmx
    TUTOR_IMAGES: openedx mfe
    GITHUB_REPO: overhangio/tutor-mexicoxmx

stages:
  - build
  - deploy


deploy_prod:
  stage: deploy
  script:
    - cp -rf * $TUTOR_DIR
  tags:
    - edx
  only:
    refs:
      - master
