variables:
    TUTOR_PLUGIN: mexicoxmx
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: mexicoxmx
    TUTOR_IMAGES: openedx mfe
    GITHUB_REPO: mexicox/tutor-indigo

stages:
  - build
  - deploy


deploy_prod:
  stage: deploy
  script:
    - rm -rf "$(tutor config printroot)/env/build/openedx/themes/indigo/*"
    - cp -rf "$(tutor config printroot)/env/build/openedx/themes/indigo/"
  tags:
    - edx
  only:
    refs:
      - master
